sudo: required

language: c

services:
  - docker

addons:
  firefox: "latest"
  sauce_connect:
    no_ssl_bump_domains: all

before_script:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make all

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    tags: true

notifications:
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master