sudo: required

language: c

env:
  matrix:
    - PLATFORM=Linux BROWSER=chrome
    - PLATFORM="Windows 10" BROWSER=firefox
    - PLATFORM="OS X 10.10" BROWSER=safari

services:
  - docker

addons:
  firefox: "latest"
  sauce_connect:
    no_ssl_bump_domains: all

before_script:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - BASEURL=http://127.0.0.1:9500 PLATFORM=$PLATFORM BROWSER=$BROWSER make all

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    tags: true

notifications:
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4#jupyter-declwidgets
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
    - issue123
