sudo: required

language: c

services:
  - docker

addons:
  firefox: "latest"

before_script:
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - make test-js-remote
  - make test-py
  - make test-scala
  - make sdist
  - make install
  - make system-test BASEURL=http://127.0.0.1:9500

notifications:
  slack: cloudet:rMfRKhvsbZuCIRZpTct3kBI4#urth-widgets
  email:
    on_success: change
    on_failure: always

branches:
  only:
    - master
